### ISSUE TITLE
Is Kickstarter denying API access?

### ISSUE THREAD

**Issue by tk5446** [markolson/kickscraper#30]
All of a sudden I am getting the following error when trying to get the client:

RuntimeError (Login does not match any of our records.)

I tried two separate kickstarter accounts. Is anyone else getting this?

**Comment by benrugg** [comment]
Kickstarter changed their api a few days ago which caused this problem. Luckily, it's now fixed with a change to kickscraper! ...and I just realized we didn't push this fix to the gem. If you need the fix right now, replace the line in your gemfile with a reference to this github repo instead of the gem. I'll push the newest version to the gem as soon as I can.

**Comment by benrugg** [comment]
Ok, I just published the new version, so now you can just update kickscraper (to version 0.2.1) and you should be good to go.

**Comment by tk5446** [comment]
awesome. Thanks @benrugg !!
