### ISSUE TITLE
Kickstarter csv

### ISSUE THREAD

**Issue by mrGreenbean** [markolson/kickscraper#35]
Hello guys, just looking to do a school paper - if possible, could someone upload the latest csv file? Noticed a few dropbox links here - though they seem to have disappeared. It would be super appreciated!

Thanks

**Comment by benrugg** [comment]
Here you go. I'll leave this link up for a bit:

https://www.dropbox.com/s/75rxb32xdtipjbd/kickstarter%20projects.csv.zip?dl=0

One quick note... On Nov 10th of this year, Kickstarter changed their API and it broke part of the way I'm collecting data. So for any projects that have finished on that date or later, they are inaccurately marked in my data as "deleted" and their final backer count and pledged amount are just slightly off.

**Comment by mrGreenbean** [comment]
Hi Ben, that's super helpful! Do you by any chance have any csv data from just before the 10th Nov?

(Just wondering if the 10th Nov bug is possible to fix in the future?)

**Comment by benrugg** [comment]
Yeah, there is 2.5 years worth of data in that CSV. And only projects ending after Nov 10th have the slight inaccuracy.

At some point I am hoping to make a workaround for the API change and fix the data, but I won't have time for a while, unfortunately.

**Comment by mrGreenbean** [comment]
Keep up the good work Ben! ☺ will keep an eye here in case there is development.

Have a good weekend,

**Comment by ChckNrrs** [comment]
Hey benrugg and mrGreenbean,

my name is Richard, I'm a German student and I'm looking for an current data set of kickstarter projects for my master thesis. Actually I have one which ends in September 2015. 
@benrugg Here and in another thread I saw, that you provide such data sets, but the download links do not work anymore. 
Would it be possible, that you upload the .cvs from above again or, if you fixed the bug, a later one?

This would help me so  much!
Best regards!
Richard

**Comment by benrugg** [comment]
Hey @ChckNrrs, sure thing... I just exported the projects (up to date) and put them here temporarily:

https://www.dropbox.com/s/75rxb32xdtipjbd/kickstarter%20projects.csv.zip?dl=0

(see the note above about the slight inaccuracies for projects ending Nov 10th and later)

**Comment by ChckNrrs** [comment]
Thank you very much @benrugg!

**Comment by gmanueltp** [comment]
Hello @benrugg and @mrGreenbean ,

As many in this post, I am also working on my master thesis about kickstarter, my bottleneck is the data and I would trully appreciate if you could help me out with the csv file. I had checked the other links but they wont open.
Thanks a lot in advanced!
My best wishes for your projects,
Guillermo

**Comment by benrugg** [comment]
Now that this is coming up so often, I'll try to put some work into an automated export of this data, so I can just post it somewhere, and so we don't have to clog up the github threads...

But for now @gmanueltp, here's the latest dump of project data: https://www.dropbox.com/s/75rxb32xdtipjbd/kickstarter%20projects.csv.zip?dl=0

**Comment by gmanueltp** [comment]
Thanks a lot @benrugg I really appreciate it! Keep the good work!!

**Comment by benrugg** [comment]
You're welcome :-) Let me know if you do something cool with it. I love seeing what everyone has been creating/researching with this kickstarter data.

**Comment by gmanueltp** [comment]
lll do it @benrugg thanks!! Ill be working on it!

**Comment by samronsin** [comment]
Hi @benrugg, I did this project with the help of your data: http://www.axplusb.com/search
I'll update the data soon, thanks a lot for sharing this!

**Comment by benrugg** [comment]
Wow @samronsin, this is is really cool. I love the visualization of that data. Great project!

**Comment by rai1234** [comment]
@benrugg thanks so much for the dataset you have uploaded. Can you provide me with the textual content of the data these campaigns provide. I am a student and would love to do some analysis.

**Comment by benrugg** [comment]
You know what... The info in that dataset is the only content I have. I don't believe you can easily scrape the textual content from Kickstarter.

**Comment by Rgui** [comment]
Hi everyone,
Does any of you know any dataset on Kickstarter that also crawled the community data (meaning the country of origin and the number of backers) and/or the number of updates and comments? 
Or a dataset with the daily updates on the number of backers and the daily amount raised by a set of projects?

**Comment by benrugg** [comment]
@Rgui - I've got data that shows some of what you're asking for. You can get it at the last dropbox link (above) that I posted.

**Comment by vonBlasberg** [comment]
Hello!

Does anyone have an idea if there is a data set available which includes the comments (text) from all successful campaigns? Thanks!

**Comment by benrugg** [comment]
@vonBlasberg - I don't have that data. If you end up finding it, let me know!

**Comment by dragoon3** [comment]
@benrugg Hello, I'm a year-two univiersity business student from Asia, recently I was doing a small class report about data analysis in Kickstarer, I've downloaded the previous dataset you've already uploaded ( covering to 08/2016), I really appreciate your csv dateset, it helps me a lot to build some statistical model, but now I really want the latest csv dataset since there are some new Asia projects coming out.  If you could upload the latest csv file or automated export site , I would be very grateful. 

Thanks a lot in advanced!

**Comment by benrugg** [comment]
@dragoon3 Sure thing. I just uploaded a new version at that same link above.

**Comment by dragoon3** [comment]
@benrugg First of all, thanks a lot! I have recently conducted statistical analysis of this dataset and found many interesting pattern, I would upload my findings after finishing this class report. 
 I'm really interested in the process of using this code file to get data from the web and build a dataset transformed to csv, could you simply explained how this code file works? (since I'm not familiar with coding, still don't have a clue how to run it)

In addition, can this code file gernerate data including reward level, avg_price, min_price, %backed_two	%backed_ten, %backed_hundred, num_comments?

**Comment by benrugg** [comment]
Hi @dragoon3 - I'm definitely curious to see the patterns and analysis you've done with the data. Post that for sure!

The project data that I have is really just pulled directly from Kickstarter. If you wanted to do average price, min price or any other analysis, you'd have to do that in Excel or something. Also, Kickstarter doesn't make any of the detailed backer data available, so the only data is just the basic info on each project.

**Comment by marcosmercado** [comment]
@benrugg Hello! Thanks for the amazing data! Do you have any up to date data?

I am working on identifying the gender of the person behind each project and for that I need the name of the person, are you pulling this data in any way?

Thank you for all your work!

**Comment by benrugg** [comment]
Hi @marcosmercado - Unfortunately, no... I don't have the name for any project creators. I'm not sure if Kickstarter offers that information easily in their API. Sorry!

**Comment by Piedjoo** [comment]
Hi @benrugg, amazing that you're keeping track of all the data! Do you happen to have data on the required returns on the projects as well?

**Comment by benrugg** [comment]
@Piedjoo what kind of info are you thinking? The "goal" data for each project is what dollar amount they need to reach for the project to be successful. Were you asking about that or something else?

**Comment by Piedjoo** [comment]
@benrugg Tnx for your quick reply! What I meant was the return the projects offer. Lets say a project wants to raise $100K in debt and offers a 6% return on it. I would like to use the data to investigate the cost of capital related to crowdfunding.. Thanks!

**Comment by benrugg** [comment]
@Piedjoo ah, yeah, that would be great data. As far as I know, Kickstarter doesn't allow projects to offer debt or pay interest to their backers. I think a couple of the other crowdfunding sites are known for that. (Let me know if I'm wrong!)

**Comment by katekol** [comment]
Hi guys! @benrugg do you happen to have an updated dataset (in csv format) of the kickstarter projects? I'm writing my master thesis on crowdfunding and I desperately need data... Plus, I've tried to download and open the dropbox files you updated above but excel cracks every time I try to import them, why so?

**Comment by yauhenibankouski** [comment]
Hey guys! @benrugg I would be reall happy if you could share the newest Kickstarter database? Also, do you think it is possible to scrape more info from Kickstarter, for example I need to research whether the projects that have video, comments and updates outperform those that do no have as well as the number of friends of founder affects the success of the campaign.And finally make the cross-region comparison

**Comment by benrugg** [comment]
@katekol and @yauhenibankouski - I've updated the shared csv file with the latest data. 

If excel is crashing, it's probably because it can't import such a large file. You should be able to find some way of importing only part of it, or using a different app to split the file into pieces.

There isn't an easy way to get other data like video, comments or friends. Sorry!

**Comment by marianna240296** [comment]
Where can I find the most updated data set of the kickstarter projects? @benrugg 
I'll start doing my thesis on crowdfunding soon and I would really appreciate to have the data available for running the analysis

**Comment by benrugg** [comment]
@marianna240296 - the most updated file is still at the dropbox link in this thread. It's sort of buried now, I guess, so I'll post it again:

https://www.dropbox.com/s/75rxb32xdtipjbd/kickstarter%20projects.csv.zip?dl=0

**Comment by marianna240296** [comment]
Thank you so much for sharing these data @benrugg

Il 21 feb 2017 6:18 PM, "Ben Rugg" <notifications@github.com> ha scritto:

**Comment by jcsouth** [comment]
@benrugg Your data set is super helpful. I'm interested in analyzing the stats just for journalism projects (I teach journalism in the US). When I filter the file you posted for journalism as a main or sub category, I find 845 projects -- which is a decent size set but far short of the 4,262 journalism projects that Kickstarter says have been posted (https://www.kickstarter.com/help/stats ... 917 successful, 3,345 failed). Any thoughts there?

**Comment by benrugg** [comment]
Hey @jcsouth -

I just looked into this... it turns out there is an answer, but it's an unsatisfying one. Apparently just a few months after I began collecting data, Kickstarter reworked all their categories. They expanded them to include many more sub categories than they had before (including niche sub categories like "bacon").

When they did that, they also changed the way their API returned data, and unfortunately we never updated our code to match it. It looks like the vast majority of my data incorrectly has main category where it should be sub category. (For example, showing "Childrenswear" as the main category, when it should be "Fashion" as the main and "Childrenswear" as the sub).

This is especially problematic for a few categories, and journalism is one of them. If you search Kickstarter's categories, you can see all main/sub categories. (Go to https://www.kickstarter.com/discover/categories/journalism and then click "Journalism" and scroll down and you can expand each main category one by one). 

Journalism has just a few sub categories: Audio, Photo, Print, Video, Web. So in theory you could search my data for projects with each of those in the main category field (and also include the ones with "Journalism" in the main category field), and then you'd have all Journalism projects.

The problem is that "Web" is also a sub category of "Technology". My data has 3787 projects listed as "Web". Some of those are Journalism/Web and the rest are Technology/Web. At this point with the data I have, I don't know of any way to accurately separate them out.

(Also, one small additional source of discrepancy between my data and Kickstarter's is that I didn't start collecting info until June 2013.)

Depending on your purposes, hopefully you can still use the data in some form.

**Comment by AccountingResearcher** [comment]
Hi @benrugg ,

Thanks for your hard work. I have a question. When I look at the projects between 2009 and 2013 (excluding 2013), I see only successful projects. Am I right? I just want to be sure about the data I have. 

Again thanks a lot

**Comment by benrugg** [comment]
@AccountingResearcher - Yeah, I'm not sure I ever made that clear. Once the scraping system was active (spring or summer 2013), I started collecting all projects (so any data after that is comprehensive). But then I went back and tried to find any past kickstarter projects and add them as well. The huge caveat is that it was only easy to collect successful (and notable/popular) projects from the past. So anything before that time is incomplete.

**Comment by benrugg** [comment]
By the way @jcsouth, I'm working on updating my code to go back and gather accurate main and sub categories for all projects. I think within a day or two I'll have it all, and I'll post the new data.

**Comment by jcsouth** [comment]
Thanks, @benrugg. I've been noodling around with different ways to focus my research. The backdrop is that there's been a big shakeout in crowdsourcing platforms for journalism in recent years. A lot of start-ups (Spot.us, Beacon, Contributoria) have all folded, leaving Kickstarter as the default for journalists seeking funding. So that's why I'm interested in looking at funding trends for Kickstarter journalism projects by year since, say, 2013: projects launched, success rates, amounts sought, amounts raised ... I wonder if there was an uptick in success over the past year with all the controversy over "fake news" and "alternative facts." (Might be too soon to measure, but worth a look.) Anyway -- thanks for whatever help you can provide on the data front. I'll credit you, of course, in any academic articles I might write off the data.

**Comment by benrugg** [comment]
@jcsouth, that's a really cool project. I'd love to see what you end up finding. I'll let you know when the data is up-to-date. (It's taking longer because Kickstarter limits the speed at which I can request info).

**Comment by benrugg** [comment]
Ok, I've finished updating all the projects with their correct main/sub categories. @jcsouth, you should now be able to look at just the Journalism projects and the numbers should be a lot closer to what Kickstarter reports.

The csv is at the same link (above).

**Comment by jcsouth** [comment]
Thanks again, @benrugg. Sorry for the delayed reply -- grading midterms, etc. I'll wade into this this week. Cheers.

**Comment by madelainegur** [comment]
Hi @benrugg! I am currently working on my thesis and would find it super helpful if you could re-post the cvs file here again. I will mention you among the people who helped in the thesis :D

**Comment by benrugg** [comment]
Hi @madelainegur - here's the latest version: https://www.dropbox.com/s/75rxb32xdtipjbd/kickstarter%20projects.csv.zip?dl=0

**Comment by Nishantkumark** [comment]
@benrugg @madelainegur Hi Ben the column names are kind of confusing. Do we have any information about what each column represents ?

**Comment by Nishantkumark** [comment]
@madelainegur I am working on a kickstarter data for my final project. I am planning to use R and use machine learning to it. How are you planning to approach it ?

**Comment by jcsouth** [comment]
Hi, @benrugg (@madelainegur and @Nishantkumark). Ben, I've been meaning to tell you something: I parsed the data that your scraper produced into a spreadsheet and hit a few snags. Apparently, some of data in certain fields have **quotation marks and commas** -- and so those rows blow up; they won't parse correctly. (If you open the CSV file in Excel, you'll see what I mean.) Could you use a different delimiter -- like a pipe (|) or a tilde (~)? I think that would solve the problem and produce a file that would flow seamlessly into Excel or any DB manager.

**Comment by benrugg** [comment]
@Nishantkumark - a fair amount of the column names are actually just from the project I use the data for - www.jumpkick.me. You can ignore those. The rest should be pretty self-explanatory kickstarter-related fields.

**Comment by benrugg** [comment]
@jcsouth - hmm, that's no good. Excel should be able to handle any kind of delimiting, because any commas or quotes in the values should be escaped. Here's a new copy delimited by a pipe. Hopefully that'll work in Excel... 

https://www.dropbox.com/s/1ya53uunkq0ge4d/kickstarter%20projects%20-%20pipe%20delimited.csv.zip?dl=0

**Comment by madelainegur** [comment]
@Nishantkumark Hi there, sorry for the late response. I am studying finance, so my initial plan was to find the factors that influence the success of a campaign. I only chose a specific category and added more data manually, but since I don't really know ho to use R and currently have also no time, I will probably do just a logit regression model. (for now there is a strong correlation between many variables so I will have to think of something else) However I'd like to see your results when you're done.

**Comment by Nishantkumark** [comment]
@madelainegur Hey sure. Can discuss on it little further. Can you mail me at nishant_kumark@yahoo.com

**Comment by hannahwen** [comment]
@benrugg  hi ben, have you also scraped the data about the project creators? e.g., information about biography, backed_projects_count , created_projects_count ,  social as mentioned in the WIKI?

**Comment by benrugg** [comment]
@hannahwen, I didn't scrape anything about the project creators, because I didn't need it for the specific project I was working on. Sorry!
